# Generated by Django 3.0.3 on 2020-03-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all',
            new_name='complete',
        ),
    ]
