# Generated by Django 3.0.3 on 2020-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200314_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='card_type',
            field=models.CharField(choices=[('trending_posts', 'LATEST_POSTS'), ('events', 'EVENTS'), ('coupons', 'COUPONS'), ('category', 'CATEGORY'), ('most_popular', 'MOST_POPULAR'), ('explore', 'EXPLORE')], default='trending_posts', max_length=100),
        ),
    ]
