# Generated by Django 3.0.3 on 2020-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200317_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='card_type',
            field=models.CharField(choices=[('trending_posts', 'LATEST_POSTS'), ('events', 'EVENTS'), ('coupons', 'COUPONS'), ('category', 'CATEGORY'), ('most_popular', 'MOST_POPULAR'), ('blogs', 'BLOGS')], default='trending_posts', max_length=100),
        ),
    ]
