# Generated by Django 3.0.3 on 2020-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_complete_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='complete',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
