# Generated by Django 3.0.3 on 2020-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20200326_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete',
            old_name='date',
            new_name='organized_by',
        ),
        migrations.AddField(
            model_name='complete',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complete',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complete',
            name='card_type',
            field=models.CharField(choices=[('trending_posts', 'LATEST_POSTS'), ('events', 'EVENTS'), ('coupons', 'COUPONS'), ('category', 'CATEGORY'), ('most_popular', 'MOST_POPULAR'), ('blogs', 'BLOGS'), ('blog_articles', 'BLOG_ARTICLES')], default='trending_posts', max_length=100),
        ),
    ]
